Add-Type -AssemblyName System.Drawing
$origBitmap = New-Object System.Drawing.Bitmap("c:\Users\NOVCAL\Drilling-Rig\frontend\public\rig3d.png")
$size = New-Object System.Drawing.Size(256, 256)
$bitmap = New-Object System.Drawing.Bitmap($origBitmap, $size)
$iconStream = New-Object System.IO.FileStream("c:\Users\NOVCAL\Drilling-Rig\DrillbitTwin.ico", [System.IO.FileMode]::Create)
$iconStream.WriteByte(0)
$iconStream.WriteByte(0)
$iconStream.WriteByte(1)
$iconStream.WriteByte(0)
$iconStream.WriteByte(1)
$iconStream.WriteByte(0)
$iconStream.WriteByte(0)
$iconStream.WriteByte(0)
$iconStream.WriteByte(0)
$iconStream.WriteByte(0)
$iconStream.WriteByte(0)
$iconStream.WriteByte(0)
$iconStream.WriteByte(0)
$iconStream.WriteByte(0)
$ms = New-Object System.IO.MemoryStream
$bitmap.Save($ms, [System.Drawing.Imaging.ImageFormat]::Png)
$ms.Position = 0
$length = $ms.Length
$iconStream.Write([BitConverter]::GetBytes([int]$length), 0, 4)
$iconStream.Write([BitConverter]::GetBytes([int]22), 0, 4)
$ms.CopyTo($iconStream)
$iconStream.Close()
$ms.Close()
$bitmap.Dispose()
$origBitmap.Dispose()
